[package]
name = "ppi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
cli-table = "0.4.7"
nom = "7.1.3"
round = "0.1.2"
